// import Navbar from "./components/Navbar";
import { Card, Row, Col } from "antd";
import {
  CodeOutlined,
  DoubleRightOutlined,
  ArrowRightOutlined,
  CheckCircleOutlined,
} from "@ant-design/icons";
// import { useState } from "react";
import Head from "next/head";
// import Image from "next/image";

const Homepage = () => {
  return (
    <div>
      {/* header */}
      <Head>
        <title>Aladintech.co</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="logo.png" />
      </Head>
      {/* hero */}
      <div className="hero-section">
        {/* <Navbar /> */}
        <div className="d1">
          <p>We build top quality products.</p>
        </div>
        <div className="d2">
          <span>Build </span>
          <span className="hero-text">Better,</span>
        </div>
        <div className="d2">
          <span className="hero-logo">
            <CodeOutlined />
            {/* >_ */}
          </span>
          <span> Build </span>
          <span className="hero-text">Faster.</span>
        </div>
        <div className="d3">
          <h3>Providing systems and comprehensive solutions for Telecom</h3>
        </div>
        <div className="d3">
          <button className="get-started-btn">
            <DoubleRightOutlined />
            <span> Get Started</span>
          </button>
          <button className="about-btn">
            <span className="about-icon">
              <ArrowRightOutlined />
            </span>
            <span> About us</span>
          </button>
        </div>

        <div className="wwd">
          <p className="wwd-text">Find more about</p>
          <h1>What we do</h1>
          <div className="wwd-card-wrapper">
            <Row gutter={16}>
              <Col span={8}>
                <Card
                  // title="Out source"
                  bordered={false}
                  cover={
                    <img
                    // width={250}
                    // height={250}
                      alt=""
                      src="https://thumbs.dreamstime.com/b/outsourcing-outline-icon-thin-line-concept-element-customer-service-icons-collection-creative-outsourcing-icon-mobile-158875806.jpg"
                    />
                  }
                >
                  Outsouceing
                </Card>
              </Col>
              <Col span={8}>
                <Card
                  bordered={false}
                  cover={
                    <img
                      alt=""
                      src="https://thumbs.dreamstime.com/b/outsourcing-outline-icon-thin-line-concept-element-customer-service-icons-collection-creative-outsourcing-icon-mobile-158875806.jpg"
                    />
                  }
                >
                  VAS
                </Card>
              </Col>
              <Col span={8}>
                <Card
                  bordered={false}
                  cover={
                    <img
                      alt=""
                      src="https://thumbs.dreamstime.com/b/outsourcing-outline-icon-thin-line-concept-element-customer-service-icons-collection-creative-outsourcing-icon-mobile-158875806.jpg"
                    />
                  }
                >
                  Platform
                </Card>
              </Col>
            </Row>
          </div>
        </div>
        {/* why us */}
        <div className="why-us">
          <h3 className="why-us-title">
            Why choose us <CheckCircleOutlined />
          </h3>
          <h3>This is some text.</h3>
          <p>Just testing.</p>
          <div className="wwd-card-wrapper">
            <Row gutter={16}>
              <Col span={8}>
                <Card
                  // title="Out source"
                  bordered={false}
                  cover={
                    <img
                      alt=""
                      src="https://thumbs.dreamstime.com/b/outsourcing-outline-icon-thin-line-concept-element-customer-service-icons-collection-creative-outsourcing-icon-mobile-158875806.jpg"
                    />
                  }
                >
                  Outsouceing
                </Card>
              </Col>
              <Col span={8}>
                <Card
                  bordered={false}
                  cover={
                    <img
                      alt=""
                      src="https://thumbs.dreamstime.com/b/outsourcing-outline-icon-thin-line-concept-element-customer-service-icons-collection-creative-outsourcing-icon-mobile-158875806.jpg"
                    />
                  }
                >
                  VAS
                </Card>
              </Col>
              <Col span={8}>
                <Card
                  bordered={false}
                  cover={
                    <img
                      alt=""
                      src="https://thumbs.dreamstime.com/b/outsourcing-outline-icon-thin-line-concept-element-customer-service-icons-collection-creative-outsourcing-icon-mobile-158875806.jpg"
                    />
                  }
                >
                  Platform
                </Card>
              </Col>
            </Row>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Homepage;
